blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                    self).get_queryset().filter(status='published')


class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    
    STATUS_CHOICES = {
        ('draft', 'Draft'),
        ('published', 'Published'),
    }
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                                on_delete=models.CASCADE,
                                related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10,
                                choices=STATUS_CHOICES,
                                default='draft')
    
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[
                            self.publish.year,
                            self.publish.month,
                            self.publish.day,
                            self.slug
                        ])
    
    class Meta:
        ordering = ('-publish',)

    def	__str__(self):
        return	self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,
                            on_delete=models.CASCADE,
                            related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
import django
from django.core import paginator
from django.core.checks import messages
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


# We have replace this view with our classed based view PostListView
def post_list(request):
    posts = Post.published.all()
    paginator = Paginator(posts, 3) # 3 posts in per page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer we are goign to set it to 1
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range we are going to deliver the last page
        posts = paginator.page(paginator.num_pages)
    
    return render(request,
                    'blog/post/list.html',
                    {
                        'page': page,
                        'posts': posts                
                    })


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                            slug=post,
                            status='published',
                            publish__year=year,
                            publish__month=month,
                            publish__day=day)
    
    # all the active comments
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # comment get posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # creating comment object and not saving in database
            new_comment = comment_form.save(commit=False)

            # assigning the current post to comment
            new_comment.post = post

            # saving the comment to databse
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request,
                    'blog/post/detail.html',
                    {
                        'post': post,
                        'comments': comments,
                        'new_comment': new_comment,
                        'comment_form': comment_form
                    })


def post_share(request, post_id):
    # retrive post usign id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # forms was submitted
        form = EmailPostForm(request.POST)

        if form.is_valid():
            # forms validated
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recomends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            messages = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, messages, 'rajesh.umedberwal@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Importing CSS From Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% include 'blog/navbar.html' %}
  <div class="mb-3"></div>
  {% block content %}
  {% endblock %}

</body>
</html>

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/blog">Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
    </div> -->
  </div>
</nav>

blog/templates/blog/pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{	page.previous_page_number	}}">Previous</a></li>
    {% endif %}
    <li class="page-item" aria-current="page">
      <a class="page-link">
        Page	{{ page.number }}	of	{{ page.paginator.num_pages }}.
      </a>
    </li>
    {% if page.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{	page.next_page_number	}}"">Next</a></li>
    {% endif %}
  </ul>
</nav>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
	<p>
	  Published	{{	post.publish	}}	by	{{	post.author	}}
	</p>
	{{	post.body|linebreaks	}}
	<p>
		<a href="{% url "blog:post_share" post.id %}">
			Share this post.
		</a>
	</p>

	{% with comments.count as total_comments %}
		<h2>
			{{ total_comments }} comment{{ total_comments|pluralize }}
		</h2>
	{% endwith %}
	{% for comment in comments %}
		<p>
			Comment {{ forloop.counter }} by {{ comment.name }}
			{{ comment.created }}
		</p>
		{{ comment.body|linebreaks }}
	{% empty %}
		<p>There is no comment yet.</p>
	{% endfor %}

	{% if new_comment %}
		<p>Your comment has been added</p>
	{% else %}
		<h2>Add a new comment</h2>
		<form action="." method="POST">
			{{ comment_form.as_p }}
			{% csrf_token %}
			<input type="submit" value="Add Comment">
		</form>
	{% endif %}
{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% block title %}MyBlog{% endblock %}

{% block content %}
  {% for post in posts %}
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-8">
          <div class="card-body">
            <a href="{{ post.get_absolute_url }}">
              <h5 class="card-title">{{ post.title }}</h5>
            </a>
            <p class="card-text"><small class="text-muted">Author: {{ post.author.first_name }} {{ post.author.last_name }}</small></p>
            <p class="card-text">{{ post.body | truncatewords:20|linebreaks }}</p>
            <p class="card-text"><small class="text-muted">Published: {{ post.publish }}</small></p>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  {% include 'blog/pagination.html' with page=page_obj %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share A Post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>Post Shared Successfully</h1>
    <p>
      "{{ post.title }}" was sent Successfully to {{ form.cleaned_data.to }}
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="POST">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send Post">
    </form>
  {% endif %}
{% endblock %}